[tool.ruff]

target-version = "py39"

extend-select = [
	"B",
	"C",
	"I",
	"PLC",
	"SIM",
	"UP",
	"W",
]

exclude = [
	"extensions",
	"extensions-disabled",
]

ignore = [
	"C408", # Rewrite as a literal
	"C408", # Rewrite as a literal
	"C901", # Function is too complex
	"C901", # Function is too complex
	"E501", # Line too long
	"E731", # Do not assign a `lambda` expression, use a `def`
	"I001", # Import block is un-sorted or un-formatted
	"SIM117", # use a single `with` (doesn't look good with gradio)
	"W605", # invalid escape sequence, messes with some docstrings
]

[tool.ruff.per-file-ignores]
"webui.py" = ["E402"] # Module level import not at top of file

[tool.ruff.flake8-bugbear]
# Allow default arguments like, e.g., `data: List[str] = fastapi.Query(None)`.
extend-immutable-calls = ["fastapi.Depends", "fastapi.security.HTTPBasic"]
